export class ModelOffers {
    constructor(
        public EAN: any,
        public Stock: any,
        public Price: any,
        public DiscountPrice: any,
        public AverageFreightCost: any,
        public PromiseDelivery: any,
        public IsFreeShipping: any,
        public IsEnviosExito: any,
        public IsFreightCalculator: any,
        public Warranty: any,
        public IsLogisticsExito: any,
        public IsUpdatedStock: any,
        public errorRow: boolean,
        public errorEan?: boolean,
        public errorStock?: boolean,
        public errorPrice?: boolean,
        public errorDiscountPrice?: boolean,
        public errorAverageFreightCost?: boolean,
        public errorPromiseDelivery?: boolean,
        public errorIsFreeShipping?: boolean,
        public errorIsEnviosExito?: boolean,
        public errorIsFreightCalculator?: boolean,
        public errorWarranty?: boolean,
        public errorIsLogisticsExito?: boolean,
        public errorIsUpdatedStock?: boolean,
        public ComboQuantity?: any,
        public EanCombo?: any,
        public errorEanCombo?: boolean,
        public errorComboQuantity?: boolean,
    ) { }
}
